services:
  ytclone:
    build: .
    container_name: ytclone
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./.env:/app/.env
      - ./client_secret.json:/app/client_secret.json
      - ./uploads_state.json:/app/uploads_state.json
      - ./uploaded.txt:/app/uploaded.txt
      - ./temp:/app/temp
